In [1]:
import numpy as np

In [2]:
#1
with open('HW.npy', 'wb') as f:
    np.save(f, np.array(range(30)))
    np.save(f, np.array([2,3,5]))

In [3]:
x = np.array(range(30))
y = np.array([2,3,5])

with open('D06HW.npz', 'wb') as f:
    np.savez(f, array1=x, array2=y)

In [4]:
#2
npzfile = np.load('D06HW.npz')
type(npzfile) 

numpy.lib.npyio.NpzFile

In [5]:
npzfile.files

['array1', 'array2']

In [6]:
print(npzfile['array1'])
print(npzfile['array2'])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
[2 3 5]


In [7]:
z = np.array(range(10))
z

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
with open('D06HW.npz', 'wb') as f:
    np.savez(f, array1=x, array2=y, array3=z)

In [9]:
npzfile = np.load('D06HW.npz')
type(npzfile) 

numpy.lib.npyio.NpzFile

In [10]:
npzfile.files

['array1', 'array2', 'array3']

In [11]:
print(npzfile['array1'])
print(npzfile['array2'])
print(npzfile['array3'])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
[2 3 5]
[0 1 2 3 4 5 6 7 8 9]
