In [1]:
import numpy as np

In [2]:
name_list = ['小明','小華','小菁','小美','小張','John','Mark','Tom']
sex_list = ['boy','boy','girl','girl','boy','boy','boy','boy']
weight_list = [67.5,75.3,50.1,45.5,80.8,90.4,78.4,70.7]
rank_list = [8,1,5,4,7,6,2,3]
myopia_list = [True,True,False,False,True,True,False,False]

In [3]:
#1. 將上列 list 依照['name', 'sex', 'weight', 'rank', 'myopia']順序擺入 array，並且資料型態順序擺入[Unicode,Unicode,float,int,boolean]

In [4]:
dt = np.dtype({'names':('Name', 'sex', 'weight', 'rank', 'myopia'), 'formats':((np.str_, 4), (np.str_, 4), np.int32, int, 'U5')})
dt

dtype([('Name', '<U4'), ('sex', '<U4'), ('weight', '<i4'), ('rank', '<i8'), ('myopia', '<U5')])

In [5]:
A = np.zeros(8, dtype=dt)
A

array([('', '', 0, 0, ''), ('', '', 0, 0, ''), ('', '', 0, 0, ''),
       ('', '', 0, 0, ''), ('', '', 0, 0, ''), ('', '', 0, 0, ''),
       ('', '', 0, 0, ''), ('', '', 0, 0, '')],
      dtype=[('Name', '<U4'), ('sex', '<U4'), ('weight', '<i4'), ('rank', '<i8'), ('myopia', '<U5')])

In [6]:
A['Name'] = name_list
A['sex'] = sex_list
A['weight'] = weight_list
A['rank'] = rank_list
A['myopia'] = myopia_list

In [7]:
print(A)

[('小明', 'boy', 67, 8, 'True') ('小華', 'boy', 75, 1, 'True')
 ('小菁', 'girl', 50, 5, 'False') ('小美', 'girl', 45, 4, 'False')
 ('小張', 'boy', 80, 7, 'True') ('John', 'boy', 90, 6, 'True')
 ('Mark', 'boy', 78, 2, 'False') ('Tom', 'boy', 70, 3, 'False')]


In [ ]:
#2. 呈上題，將 array 中體重(weight)數據集取出算出全部平均體重

In [8]:
B = A['weight']
B

array([67, 75, 50, 45, 80, 90, 78, 70], dtype=int32)

In [9]:
np.mean(B)

69.375

In [ ]:
#3. 呈上題，進一步算出男生(sex 欄位是 boy)平均體重、女生(sex 欄位是 girl)平均體重

In [10]:
C = A[A['sex'] == 'boy']['weight']
C

array([67, 75, 80, 90, 78, 70], dtype=int32)

In [11]:
np.mean(C)

76.66666666666667

In [12]:
D = A[A['sex'] == 'girl']['weight']
D

array([50, 45], dtype=int32)

In [13]:
np.mean(D)

47.5